name: Enhancement request
description: Suggest an enhancement for this project / Improve an existing feature
title: "[Enhancement 🏗] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: today
    attributes:
      label: What is the current behavior?
      placeholder: Tell us how does the extension work today
    validations:
      required: true
  - type: textarea
    id: tomorrow
    attributes:
      label: What could be the new behavior?
      placeholder: Tell us how could the extension work tomorrow
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
