name: Question/Support request
description: Ask a question / Ask for support
title: "[Question/Support ❓] "
labels: ["question"]
body:
  - type: textarea
    id: today
    attributes:
      label: Describe your question or ask for support
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
